export const ActionTypes = {
  //auth
  USER_LOADING: "USER_LOADING",
  GET_TOKEN: "GET_TOKEN",
  SET_USER: "SET_USER",
  USER_LOGOUT: "USER_LOGOUT",
  USER_ERROR: "USER_ERROR",

  //ui
  OPEN_FORM: "OPEN_FORM",
  CLOSE_FORM: "CLOSE_FORM",

  LOGIN_FORM: "LOGIN_FORM",
  SIGNUP_FORM: "SIGNUP_FORM",

  OPEN_TRAILER: "OPEN_TRAILER",
  CLOSE_TRAILER: "CLOSE_TRAILER",

  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  CLOSE_SIDEBAR: "CLOSE_SIDEBAR",

  //firestore
  GET_FAVORITES_REQUEST: "GET_FAVORITES_REQUEST",
  GET_FAVORITES_SUCCESS: "GET_FAVORITES_SUCCESS",
  GET_FAVORITES_FAILED: "GET_FAVORITES_FAILED",

  GET_WATCHLIST_REQUEST: "GET_WATCHLIST_REQUEST",
  GET_WATCHLIST_SUCCESS: "GET_WATCHLIST_SUCCESS",
  GET_WATCHLIST_FAILED: "GET_WATCHLIST_FAILED",
};
