export const ActionTypes = {
  //genres
  GET_GENRES_REQUEST: "GET_GENRES_REQUEST",
  GET_GENRES_SUCCESS: "GET_GENRES_SUCCESS",
  GET_GENRES_FAILED: "GET_GENRES_FAILED",

  //category

  GET_NOW_PALYING_REQUEST: "GET_NOW_PLAYING_REQUEST",
  GET_NOW_PALYING_SUCCESS: "GET_NOW_PLAYING_SUCCESS",
  GET_NOW_PALYING_FAILED: "GET_NOW_PLAYING_FAILED",

  GET_POPULAR_REQUEST: "GET_POPULAR_REQUEST",
  GET_POPULAR_SUCCESS: "GET_POPULAR_SUCCESS",
  GET_POPULAR_FAILED: "GET_POPULAR_FAILED",

  GET_TOP_RATED_REQUEST: "GET_TOP_RATED_REQUEST",
  GET_TOP_RATED_SUCCESS: "GET_TOP_RATED_SUCCESS",
  GET_TOP_RATED_FAILED: "GET_TOP_RATED_FAILED",

  GET_UPCOMING_REQUEST: "GET_UPCOMING_REQUEST",
  GET_UPCOMING_SUCCESS: "GET_UPCOMING_SUCCESS",
  GET_UPCOMING_FAILED: "GET_UPCOMING_FAILED",

  //movies
  GET_MOVIES_REQUEST: "GET_MOVIES_REQUEST",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAILED: "GET_MOVIES_FAILED",

  GET_MOVIE_REQUEST: "GET_MOVIE_REQUEST",
  GET_MOVIE_SUCCESS: "GET_MOVIE_SUCCESS",
  GET_MOVIE_FAILED: "GET_MOVIE_FAILED",

  //auth
  USER_LOADING: "USER_LOADING",
  GET_TOKEN: "GET_TOKEN",
  SET_USER: "SET_USER",
  USER_LOGOUT: "USER_LOGOUT",
  USER_ERROR: "USER_ERROR",

  //ui
  /* OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "OPEN_CLOSE", */

  OPEN_FORM: "OPEN_FORM",
  CLOSE_FORM: "CLOSE_FORM",

  LOGIN_FORM: "LOGIN_FORM",
  SIGNUP_FORM: "SIGNUP_FORM",

  OPEN_TRAILER: "OPEN_TRAILER",
  CLOSE_TRAILER: "CLOSE_TRAILER",
};
