export const ActionTypes = {
  //genres
  GET_GENRES_REQUEST: "GET_GENRES_REQUEST",
  GET_GENRES_SUCCESS: "GET_GENRES_SUCCESS",
  GET_GENRES_FAILED: "GET_GENRES_FAILED",

  //category

  GET_NOW_PALYING_REQUEST: "GET_NOW_PLAYING_REQUEST",
  GET_NOW_PALYING_SUCCESS: "GET_NOW_PLAYING_SUCCESS",
  GET_NOW_PALYING_FAILED: "GET_NOW_PLAYING_FAILED",

  GET_POPULAR_REQUEST: "GET_POPULAR_REQUEST",
  GET_POPULAR_SUCCESS: "GET_POPULAR_SUCCESS",
  GET_POPULAR_FAILED: "GET_POPULAR_FAILED",

  GET_TOP_RATED_REQUEST: "GET_TOP_RATED_REQUEST",
  GET_TOP_RATED_SUCCESS: "GET_TOP_RATED_SUCCESS",
  GET_TOP_RATED_FAILED: "GET_TOP_RATED_FAILED",

  GET_UPCOMING_REQUEST: "GET_UPCOMING_REQUEST",
  GET_UPCOMING_SUCCESS: "GET_UPCOMING_SUCCESS",
  GET_UPCOMING_FAILED: "GET_UPCOMING_FAILED",

  //movies
  GET_MOVIE_REQUEST: "GET_MOVIE_REQUEST",
  GET_MOVIE_SUCCESS: "GET_MOVIE_SUCCESS",
  GET_MOVIE_FAILED: "GET_MOVIE_FAILED",
};
