export const GET_GENRES_REQUEST = "GET_GENRES_REQUEST";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_FAIL = "GET_GENRES_FAIL";

export const GET_NOW_PLAYING_REQUEST = "GET_NOW_PLAYING_REQUEST";
export const GET_NOW_PLAYING_SUCCESS = "GET_NOW_PLAYING_SUCCESS";
export const GET_NOW_PLAYING_FAIL = "GET_NOW_PLAYING_FAIL";

export const GET_POPULAR_REQUEST = "GET_POPULAR_REQUEST";
export const GET_POPULAR_SUCCESS = "GET_POPULAR_SUCCESS";
export const GET_POPULAR_FAIL = "GET_POPULAR_FAIL";

export const GET_TOP_RATED_REQUEST = "GET_TOP_RATED_REQUEST";
export const GET_TOP_RATED_SUCCESS = "GET_TOP_RATED_SUCCESS";
export const GET_TOP_RATED_FAIL = "GET_TOP_RATED_FAIL";

export const GET_UPCOMING_REQUEST = "GET_UPCOMING_REQUEST";
export const GET_UPCOMING_SUCCESS = "GET_UPCOMING_SUCCESS";
export const GET_UPCOMING_FAIL = "GET_UPCOMING_FAIL";

export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";
