//genres
export const GET_GENRES_REQUEST = "GET_GENRES_REQUEST";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_FAILED = "GET_GENRES_FAILED";

//category
export const GET_NOW_PALYING_REQUEST = "GET_NOW_PLAYING_REQUEST";
export const GET_NOW_PALYING_SUCCESS = "GET_NOW_PLAYING_SUCCESS";
export const GET_NOW_PALYING_FAILED = "GET_NOW_PLAYING_FAILED";

export const GET_POPULAR_REQUEST = "GET_POPULAR_REQUEST";
export const GET_POPULAR_SUCCESS = "GET_POPULAR_SUCCESS";
export const GET_POPULAR_FAILED = "GET_POPULAR_FAILED";

export const GET_TOP_RATED_REQUEST = "GET_TOP_RATED_REQUEST";
export const GET_TOP_RATED_SUCCESS = "GET_TOP_RATED_SUCCESS";
export const GET_TOP_RATED_FAILED = "GET_TOP_RATED_FAILED";

export const GET_UPCOMING_REQUEST = "GET_UPCOMING_REQUEST";
export const GET_UPCOMING_SUCCESS = "GET_UPCOMING_SUCCESS";
export const GET_UPCOMING_FAILED = "GET_UPCOMING_FAILED";

//movies
export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";

export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAILED = "GET_MOVIE_FAILED";
